apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJkaGFybWF0a2oiLCJwYXNzd29yZCI6IkRoNHJtNHB1dHI0IiwiZW1haWwiOiJpZ2JkaGFybWFwdXRyYUBnbWFpbC5jb20iLCJhdXRoIjoiWkdoaGNtMWhkR3RxT2tSb05ISnROSEIxZEhJMCJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: dockerhubpull
  namespace: production
type: kubernetes.io/dockerconfigjson